### ISSUE TITLE
Ideas [TODO]

### ISSUE THREAD

**Issue by talopakola** [talopakola/PlusMod-src#1]
## Main:
- [x] Animate main tools
- [x] Made a ̶P̶e̶r̶f̶e̶c̶t̶ ̶c̶o̶p̶y̶ ̶o̶f̶ ̶A̶v̶a̶r̶i̶t̶i̶a̶ mod look like my inspiration (Avaritia)
- [x] Made Infinity Pickaxe break bedrock (I forgot add this feature)...
- [x] Infinity Bow
- [x] More compatibilities
## Compatibilities:

- [x] Avaritia
- [x] MineTweaker
## Random thoughts that probably I made while in bathroom and won't enter in the game:

- [ ] Galacticraft support
- [ ] A block that can explode the entire world (this not include your PC)
- [x] Infinity Chest with infinity storage
- [ ] Iron Chest Mod support
- [x] Storage Drawers support
- [x] Infinity Banana... Ye, infinity banana
- [ ] If SpitefulFox gave me permission, use my modified Cosmic Shaders shader
- [ ] Made a entire custom dimesion with a boss that can kill even Plus and Avaritia
- [ ]  ̶S̶w̶e̶a̶r̶ ̶t̶o̶ ̶G̶o̶d̶ ̶t̶o̶ ̶f̶i̶n̶d̶ ̶a̶ ̶p̶e̶r̶s̶o̶n̶ ̶t̶o̶ ̶h̶e̶l̶p̶ ̶m̶e̶ ̶o̶n̶ ̶t̶h̶e̶ ̶m̶o̶d̶ ̶f̶o̶r̶ ̶f̶r̶e̶e̶

**Comment by talopakola** [comment]
I COMPLETE ONE TASK YEYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY

**Comment by talopakola** [comment]
for some weird reason I liked this Reality Cristal
![image](https://github.com/user-attachments/assets/95e9d87b-87d4-444a-96c4-0dc6eddb15f7)

**Comment by talopakola** [comment]
![image](https://github.com/user-attachments/assets/effa3503-dd55-4031-890b-a66a40fe778b)
![image](https://github.com/user-attachments/assets/4f04cec7-599d-4ad1-958c-e381f7a63427)

ok, i think I break the shaders...
